# permissions for end users to view webgames.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: game-operator
    app.kubernetes.io/managed-by: kustomize
  name: webgame-viewer-role
rules:
- apiGroups:
  - webgame.webgame.zjl
  resources:
  - webgames
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webgame.webgame.zjl
  resources:
  - webgames/status
  verbs:
  - get
